<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Graded lab: Time series (solutions)</title>

<script src="libs/header-attrs-2.18/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/spacelab.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<link href="libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div id="header">



<h1 class="title toc-ignore">Graded lab: Time series (solutions)</h1>

</div>


<p>This lab should be submitted to Moodle on April 21st.</p>
<p><strong>Numbers in parentheses indicate the number of points for each
question.</strong></p>
<p><strong>Total: 12 points.</strong></p>
<div id="data" class="section level2">
<h2>Data</h2>
<p>For this exercise we will use data from a flux tower located in a
black spruce forest near Chibougamau.</p>
<blockquote>
<p><strong>Reference</strong>: Bergeron, Margolis, Black, Coursolle,
Dunn, Barr, &amp; Wofsy. (2007). Comparison of carbon dioxide fluxes
over three boreal black spruce forests in Canada. Global Change Biology,
13(1), 89–107. <a
href="https://doi.org/10.1111/j.1365-2486.2006.01281.x"
class="uri">https://doi.org/10.1111/j.1365-2486.2006.01281.x</a>.</p>
</blockquote>
<p>Flux towers measure net ecosystem exchange or the amount of gas that
is exchanged between the atmosphere and the ecosystem using eddy
covariance technique.</p>
<blockquote>
<p><strong>Weblink</strong>: <a
href="https://www.neonscience.org/3d-interactive-flux-tower"
class="uri">https://www.neonscience.org/3d-interactive-flux-tower</a></p>
</blockquote>
<blockquote>
<p><strong>Weblink</strong>: <a
href="https://www.youtube.com/watch?v=CR4Anc8Mkas"
class="uri">https://www.youtube.com/watch?v=CR4Anc8Mkas</a></p>
</blockquote>
<blockquote>
<p><strong>Weblink</strong>: <a
href="https://www.neonscience.org/data-collection/flux-tower-measurements"
class="uri">https://www.neonscience.org/data-collection/flux-tower-measurements</a></p>
</blockquote>
<blockquote>
<p><strong>Weblink</strong>: <a
href="https://www.neonscience.org/data-collection/meteorology"
class="uri">https://www.neonscience.org/data-collection/meteorology</a></p>
</blockquote>
<p>We will start loading the required packages and the data.</p>
<pre class="r"><code>library(fpp3)
library(dplyr)
library(ggplot2)
library(cowplot)
EOBS_fluxnet &lt;- read.csv(&quot;../donnees/EOBS_fluxnet2.csv&quot;)
head(EOBS_fluxnet)</code></pre>
<pre><code>##   Year Day GapFilled_NEP GapFilled_R GapFilled_GEP TimeSteps
## 1 2004   1    -0.3702583   0.3702583             0        48
## 2 2004   2    -0.3226569   0.3226569             0        48
## 3 2004   3    -0.3143513   0.3143513             0        48
## 4 2004   4    -0.3108769   0.3108769             0        48
## 5 2004   5    -0.3105173   0.3105173             0        48
## 6 2004   6    -0.3069446   0.3069446             0        48</code></pre>
<p>The columns are:</p>
<ul>
<li><p><em>Year</em> is the year of the observation</p></li>
<li><p><em>Day</em> is the day of the year of the observation
(1-365)</p></li>
<li><p><em>GapFilled_NEP</em> is the daily net ecosystem productivity
(<em>umol C m-2 of stand s-1</em>)</p></li>
<li><p><em>GapFilled_R</em> is the daily ecosystem respiration (<em>umol
C m-2 of stand s-1</em>)</p></li>
<li><p><em>GapFilled_GEP</em> is the daily gross ecosystem productivity
(<em>umol C m-2 of stand s-1</em>)</p></li>
<li><p><em>TimeSteps</em> is an integer saying how many half hourly data
composed the daily aggregates</p></li>
</ul>
</div>
<div id="arima-model-for-nep" class="section level2">
<h2>1. ARIMA model for NEP</h2>
<p><strong>(1a) Create a temporal data frame (<em>tsibble</em>). As a
first step, you must add a column containing the date using the
information in <em>Year</em> and <em>Day</em>. Consult the following
website to understand how to deal with date/time data in <em>R</em>: <a
href="https://www.stat.berkeley.edu/~s133/dates.html"
class="uri">https://www.stat.berkeley.edu/~s133/dates.html</a> (1
point)</strong></p>
<pre class="r"><code>EOBS_fluxnet = mutate(EOBS_fluxnet, 
                      Date = as.Date(paste(EOBS_fluxnet$Year,EOBS_fluxnet$Day), format=&#39;%Y %j&#39;))
EOBS_fluxnet = as_tsibble(EOBS_fluxnet, index = Date)
head(EOBS_fluxnet)</code></pre>
<pre><code>## # A tsibble: 6 x 7 [1D]
##    Year   Day GapFilled_NEP GapFilled_R GapFilled_GEP TimeSteps Date      
##   &lt;int&gt; &lt;int&gt;         &lt;dbl&gt;       &lt;dbl&gt;         &lt;dbl&gt;     &lt;int&gt; &lt;date&gt;    
## 1  2004     1        -0.370       0.370             0        48 2004-01-01
## 2  2004     2        -0.323       0.323             0        48 2004-01-02
## 3  2004     3        -0.314       0.314             0        48 2004-01-03
## 4  2004     4        -0.311       0.311             0        48 2004-01-04
## 5  2004     5        -0.311       0.311             0        48 2004-01-05
## 6  2004     6        -0.307       0.307             0        48 2004-01-06</code></pre>
<p><strong>(1b) One of the problems working with daily data is to deal
with leap years. In this case we load data with constant 365 days per
year. This is a common solution to simplify the data processing,
especially in modelling. In order to add one more day per each leap year
we can use the functions <em>fill_gaps</em> (<a
href="https://www.rdocumentation.org/packages/tsibble/versions/1.0.0/topics/fill_gaps"
class="uri">https://www.rdocumentation.org/packages/tsibble/versions/1.0.0/topics/fill_gaps</a>)
and <em>tidyr::fill</em> (<a
href="https://www.rdocumentation.org/packages/tidyr/versions/1.1.3/topics/fill"
class="uri">https://www.rdocumentation.org/packages/tidyr/versions/1.1.3/topics/fill</a>).
We can specify that the added rows have <em>Day</em> equal to 366 and
<em>GapFilled_NEP</em>, <em>GapFilled_R</em>, <em>GapFilled_GEP</em>,
and <em>Year</em> equal to the value of the preceding row. (1
point)</strong></p>
<pre class="r"><code>EOBS_fluxnet = EOBS_fluxnet %&gt;%
              fill_gaps(Day = 366) %&gt;%
              tidyr::fill(GapFilled_NEP, .direction = &quot;down&quot;) %&gt;%
              tidyr::fill(GapFilled_R, .direction = &quot;down&quot;) %&gt;%
              tidyr::fill(GapFilled_GEP, .direction = &quot;down&quot;) %&gt;%
              tidyr::fill(Year, .direction = &quot;down&quot;) 
EOBS_fluxnet[EOBS_fluxnet$Day==366,]</code></pre>
<pre><code>## # A tsibble: 2 x 7 [1D]
##    Year   Day GapFilled_NEP GapFilled_R GapFilled_GEP TimeSteps Date      
##   &lt;int&gt; &lt;dbl&gt;         &lt;dbl&gt;       &lt;dbl&gt;         &lt;dbl&gt;     &lt;int&gt; &lt;date&gt;    
## 1  2004   366        -0.227       0.227             0        NA 2004-12-31
## 2  2008   366        -0.644       0.644             0        NA 2008-12-31</code></pre>
<p>Here above we visualize the two added lines for the leap years.</p>
<p><strong>(1c) Obtain a new temporal data frame (<em>tsibble</em>)
containing mean monthly values of <em>GapFilled_NEP</em>. Plot the
obtained time series and comment it. How does the time series vary over
time? What do negative values mean? (1 point)</strong></p>
<pre class="r"><code>EOBS_fluxnet_monthly &lt;- index_by(EOBS_fluxnet, month = yearmonth(Date)) %&gt;%
  summarize(GapFilled_NEP = mean(GapFilled_NEP))
head(EOBS_fluxnet_monthly)</code></pre>
<pre><code>## # A tsibble: 6 x 2 [1M]
##        month GapFilled_NEP
##        &lt;mth&gt;         &lt;dbl&gt;
## 1 2004 janv.        -0.289
## 2 2004 févr.        -0.410
## 3  2004 mars        -0.616
## 4  2004 avr.        -0.492
## 5   2004 mai         0.701
## 6  2004 juin         1.34</code></pre>
<pre class="r"><code>autoplot(EOBS_fluxnet_monthly,vars(GapFilled_NEP))</code></pre>
<p><img src="E11RE-Series_temporelles_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>In the plot we see the typical annual cycle of the productivity of a
boreal forest ecosystem with contrasted winter dormancy and strong
uptake over the growing season. The negative values during winter time
mean that the ecosystem is a carbon source (respiration higher than
photosynthesis).</p>
<p><strong>(1d) Plot the 3 time-series of daily values
(<em>GapFilled_NEP</em>, <em>GapFilled_R</em>, <em>GapFilled_GEP</em>),
the annual seasonality of <em>GapFilled_NEP</em> (use the daily dataset
as well as the monthly dataset providing two distinct plots), and the
trend of <em>GapFilled_NEP</em> data for each month over time (use the
monthly dataset). When does the growing season start and end at the
study site? When does the peak of photosynthesis occur? Is there any
evident trend in the mean monthly values? (1 point)</strong></p>
<pre class="r"><code>plot_grid(
    autoplot(EOBS_fluxnet, GapFilled_NEP),
    autoplot(EOBS_fluxnet, GapFilled_GEP),
    autoplot(EOBS_fluxnet, GapFilled_R),
    ncol = 1, align = &quot;v&quot;)</code></pre>
<p><img src="E11RE-Series_temporelles_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>gg_season(EOBS_fluxnet, y = GapFilled_NEP)</code></pre>
<p><img src="E11RE-Series_temporelles_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<pre class="r"><code>gg_season(EOBS_fluxnet_monthly, y = GapFilled_NEP)</code></pre>
<p><img src="E11RE-Series_temporelles_files/figure-html/unnamed-chunk-5-3.png" width="672" /></p>
<p>The growing season starts in May and ends in September. The peak of
photosynthesis is between May and July according to the year.</p>
<pre class="r"><code>gg_subseries(EOBS_fluxnet_monthly, y = GapFilled_NEP)</code></pre>
<p><img src="E11RE-Series_temporelles_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>There is no evident common trend in the monthly values. However, an
upward trend in April and two negative trends in August and September
are visible.</p>
<p><strong>(1e) Extract the several components of the
<em>GapFilled_NEP</em> daily time series (trend, seasonality, and
residuals). What is the components’ relative importance? What does it
mean? Finally, store the components into a new temporal data frame
(<em>tsibble</em>). (1 point)</strong></p>
<pre class="r"><code>decomp &lt;- model(EOBS_fluxnet, STL(GapFilled_NEP))
autoplot(components(decomp))</code></pre>
<p><img src="E11RE-Series_temporelles_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>NEP_components = components(decomp)</code></pre>
<p>The residual component is the more important showing that the daily
meteorology over the growing season strongly influences the
productivity. The second more important component is the annual
seasonality.</p>
<p><strong>(1f) Analyze the autocorrelation and the partial
autocorrelation of the <em>GapFilled_NEP</em> daily time series and of
its residual component extracted in 1e. What do you deduce from these
plots? (1 point)</strong></p>
<pre class="r"><code>plot_grid(autoplot(ACF(EOBS_fluxnet, GapFilled_NEP)), autoplot(PACF(EOBS_fluxnet, GapFilled_NEP)))</code></pre>
<p><img src="E11RE-Series_temporelles_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The autocorrelation structure of the NEP data is very long lasting
because of the clear annual seasonality.</p>
<pre class="r"><code>plot_grid(autoplot(ACF(NEP_components, remainder)), autoplot(PACF(NEP_components, remainder)))</code></pre>
<p><img src="E11RE-Series_temporelles_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The seasonal components obtained in 1e are not well adjusted to the
data because the residuals show a weekly seasonality.</p>
<p><strong>(1g) Adjust an ARIMA model to the <em>GapFilled_NEP</em>
daily time series. Let the model choose the appropriate ARIMA model.
What kind of ARIMA model is automatically selected? Do the the ARIMA
residuals meet the model’s assumptions? (1 point)</strong></p>
<pre class="r"><code>NEP_arima &lt;- model(EOBS_fluxnet, ARIMA(GapFilled_NEP))
report(NEP_arima)</code></pre>
<pre><code>## Series: GapFilled_NEP 
## Model: ARIMA(3,0,2) 
## 
## Coefficients:
##          ar1     ar2      ar3     ma1      ma2
##       0.1990  0.9568  -0.1800  0.1138  -0.8565
## s.e.  0.0306  0.0267   0.0252  0.0220   0.0214
## 
## sigma^2 estimated as 0.448:  log likelihood=-2599.64
## AIC=5211.27   AICc=5211.3   BIC=5246.35</code></pre>
<p>An ARIMA model of the type (3,0,2) is selected. This means an
autoregressive model of order 3 combined with a moving avearage model of
order 2.</p>
<pre class="r"><code>gg_tsresiduals(NEP_arima)</code></pre>
<p><img src="E11RE-Series_temporelles_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>The residuals have only few slightly significant autocorrelations.
However, they are not normally distributed because during wintertime
they are normally very low.</p>
<p><strong>(1h) Forecast and plot one additional year of
<em>GapFilled_NEP</em> daily data based on the selected model in the
previous step. (1 point)</strong></p>
<pre class="r"><code>prev_NEP &lt;- forecast(NEP_arima, h = 365)
head(prev_NEP)</code></pre>
<pre><code>## # A fable: 6 x 4 [1D]
## # Key:     .model [1]
##   .model               Date        GapFilled_NEP  .mean
##   &lt;chr&gt;                &lt;date&gt;             &lt;dist&gt;  &lt;dbl&gt;
## 1 ARIMA(GapFilled_NEP) 2011-01-01 N(-0.32, 0.45) -0.318
## 2 ARIMA(GapFilled_NEP) 2011-01-02 N(-0.31, 0.49) -0.305
## 3 ARIMA(GapFilled_NEP) 2011-01-03  N(-0.29, 0.5) -0.286
## 4 ARIMA(GapFilled_NEP) 2011-01-04 N(-0.29, 0.51) -0.292
## 5 ARIMA(GapFilled_NEP) 2011-01-05 N(-0.28, 0.52) -0.276
## 6 ARIMA(GapFilled_NEP) 2011-01-06 N(-0.28, 0.53) -0.283</code></pre>
<pre class="r"><code>autoplot(prev_NEP, EOBS_fluxnet, level = c(50, 95))</code></pre>
<p><img src="E11RE-Series_temporelles_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="arima-model-for-nep-with-external-predictors"
class="section level2">
<h2>2. ARIMA model for NEP with external predictors</h2>
<p>We will start loading meteorological data for the flux tower
site.</p>
<pre class="r"><code>My_meteo=read.delim(&quot;../donnees/EOBS_fluxnet_inmet2.txt&quot;,skip=1,header=F)
names(My_meteo)= c(&quot;Year&quot;,&quot;Day&quot;,&quot;Tmax&quot;,&quot;Tmin&quot;,&quot;Precip&quot;,&quot;CO2&quot;)
head(My_meteo)</code></pre>
<pre><code>##   Year Day       Tmax      Tmin Precip      CO2
## 1 2004   1 -14.280000 -20.70000  0.306 384.4005
## 2 2004   2 -13.340000 -17.90000  0.203 384.3611
## 3 2004   3  -1.859991 -13.34000  0.401 384.3216
## 4 2004   4  -8.299994 -24.65999  0.000 384.2822
## 5 2004   5 -18.000010 -28.14001  0.157 384.2427
## 6 2004   6 -17.900000 -20.32000  0.109 384.2033</code></pre>
<p>The columns are:</p>
<ul>
<li><p><em>Year</em> is the year of the observation</p></li>
<li><p><em>Day</em> is the day of the year of the observation
(1-365)</p></li>
<li><p><em>Tmax</em> is the daily maximum temperature
(<em>°C</em>)</p></li>
<li><p><em>Tmin</em> is the daily minimum temperature
(<em>°C</em>)</p></li>
<li><p><em>Precip</em> is the daily precipitation sum
(<em>cm</em>)</p></li>
<li><p><em>CO2</em> is daily CO2 concentration (<em>ppm</em>)</p></li>
</ul>
<p>Once you have loaded the meteorological data you must create a
temporal data frame with these data (same procedure than 1a) and gap
fill these data (same procedure than 1b).</p>
<pre class="r"><code>My_meteo = mutate(My_meteo, Date = as.Date(paste(My_meteo$Year,My_meteo$Day), format=&#39;%Y %j&#39;))
My_meteo = as_tsibble(My_meteo, index = Date)
My_meteo = My_meteo %&gt;%
  fill_gaps(Day = 366) %&gt;%
  tidyr::fill(Tmax, .direction = &quot;down&quot;) %&gt;%
  tidyr::fill(Tmin, .direction = &quot;down&quot;) %&gt;%
  tidyr::fill(Precip, .direction = &quot;down&quot;) %&gt;%
  tidyr::fill(CO2, .direction = &quot;down&quot;) %&gt;%
  tidyr::fill(Year, .direction = &quot;down&quot;)</code></pre>
<p><strong>(2a) Find the meteorological or environmental variable
(<em>Tmax</em>, <em>Tmin</em>, <em>Precip</em> or <em>CO2</em>) that
correlates the most with the <em>GapFilled_NEP</em> daily time series.
(1 point)</strong></p>
<pre class="r"><code>cor(EOBS_fluxnet$GapFilled_NEP, My_meteo[, 3:6])</code></pre>
<pre><code>##           Tmax      Tmin     Precip       CO2
## [1,] 0.4778448 0.3749279 -0.1627362 -0.150494</code></pre>
<p>The meteorological variable that correlates the most with the
<em>GapFilled_NEP</em> daily time series is the daily maximum
temperature.</p>
<p><strong>(2b) Join the flux and meteorological tables
(<em>inner_join</em>) and plot the relationship (scatterplot) between
the variable found in 2a (x-axis) and <em>GapFilled_NEP</em> (y-axis).
Comment on this relationship. (1 point)</strong></p>
<pre class="r"><code>EOBS_fluxnet &lt;- inner_join(EOBS_fluxnet, My_meteo)
ggplot(EOBS_fluxnet, aes(x = Tmax, y = GapFilled_NEP)) +
  geom_point() </code></pre>
<p><img src="E11RE-Series_temporelles_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>No carbon uptake is possible if Tmax is lower than about 3°C. After
this threshold, a positive relationship is present with an important
variability.</p>
<p><strong>(2c) Apply a linear model without any ARIMA terms including a
quadratic term for the variable found in 2a. Then, plot the model
predictions on the plot of 2b. Finally, plot the residuals of this model
as a function of time. Does the model represent the data correctly? Try
to explain why the residuals seem to be mostly positive at the beginning
of the growing season. (1 point)</strong></p>
<pre class="r"><code>NEP_climate_lm &lt;- lm(GapFilled_NEP ~ Tmax + I(Tmax^2), EOBS_fluxnet)
summary(NEP_climate_lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = GapFilled_NEP ~ Tmax + I(Tmax^2), data = EOBS_fluxnet)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.1977 -0.3494 -0.0114  0.3002  4.4637 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -2.348e-01  2.143e-02 -10.955  &lt; 2e-16 ***
## Tmax         2.701e-02  1.353e-03  19.958  &lt; 2e-16 ***
## I(Tmax^2)    4.823e-04  7.942e-05   6.073 1.44e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.7774 on 2554 degrees of freedom
## Multiple R-squared:  0.2393, Adjusted R-squared:  0.2387 
## F-statistic: 401.8 on 2 and 2554 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>ggplot(NEP_climate_lm, aes(x = Tmax, y = GapFilled_NEP)) +
  geom_point(alpha = 0.3) +
  geom_line(aes(y = fitted(NEP_climate_lm)),col=2)</code></pre>
<p><img src="E11RE-Series_temporelles_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>The quadratic polynomial model does not fit well the data which are
difficult to be represented by a simple common model for winter and
summer time. Here the quadratic polynomial model underestimates the data
for Tmax &lt; -10°C and Tmax &gt; 10°C while overestimates the data for
Tmax between -5°C and 10°C.</p>
<pre class="r"><code>ggplot(EOBS_fluxnet, aes(x = Date, y = residuals(NEP_climate_lm))) +
  geom_line()</code></pre>
<p><img src="E11RE-Series_temporelles_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>The residuals seem to be mostly positive at the beginning of the
growing season because during this period the forest productivity
strongly responds to good weather.</p>
<p><strong>(2d) Add ARIMA terms to the model of 2c and compare the AIC
of this model with the AIC of the model in 1g. Compare the ARIMA terms
selected here and in 1g. (1 point)</strong></p>
<pre class="r"><code>NEP_climate_arima &lt;- model(EOBS_fluxnet, ARIMA(GapFilled_NEP ~ Tmax + I(Tmax^2)))
report(NEP_climate_arima)</code></pre>
<pre><code>## Series: GapFilled_NEP 
## Model: LM w/ ARIMA(1,0,2) errors 
## 
## Coefficients:
##          ar1      ma1      ma2    Tmax  I(Tmax^2)
##       0.9837  -0.6791  -0.1538  0.0042     -3e-04
## s.e.  0.0046   0.0202   0.0199  0.0028      1e-04
## 
## sigma^2 estimated as 0.4478:  log likelihood=-2599.21
## AIC=5210.42   AICc=5210.45   BIC=5245.5</code></pre>
<p>The AIC of the model including Tmax is 5210.42 while the AIC of the
model in 1g is 5211.27. An ARIMA model of the type (1,0,2) is selected
here while a model of the type (3,0,2) is selected in 1g. The inclusion
of Tmax slightly improves the model.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
